-- 코드를 입력하세요
SELECT DISTINCT PRODUCT.PRODUCT_CODE, (SELECT SUM(OFFLINE_SALE.SALES_AMOUNT) * PRODUCT.PRICE FROM OFFLINE_SALE WHERE OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID GROUP BY PRODUCT.PRICE) AS SALES
FROM PRODUCT
INNER JOIN OFFLINE_SALE
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC;
